Adding "Optimize the image size" section with `kernel-slim` parent image.
OpenLiberty/guide-containerize pull request #121
Opened 2022-06-02 20:59 UTC by uhryniuk

Tested and works:
- locally
- turnip1
- cloud hosted

2022-06-06 18:29 UTC, gkwan-ibm requested changes
hi @uhryniuk 

- "Place `RUN features.sh` between the `COPY` commands in the `Dockerfile`." -> "Place `RUN features.sh` command after the `COPY` command that the configuration file is copied to the '/config/` destination directory ."
- no need to change `system` to `system-slim`
- no need to change `inventory` to `inventory-slim`
- no need to run `docker images -f`
- after `docker run...`, run `docker exec -it system /opt/ol/wlp/bin/productInfo featureInfo`, will see the required features only

2022-06-07 17:06 UTC, gkwan-ibm requested changes
@uhryniuk 
- let check the `docker images` and update its output at the end of the "Building your Docker image" subsection, for the `SIZE` column.
- at the "Optimizing the image size" section, also do the same thing. Now, the optimized size is greater than the full
- update the `testAppFinish.sh` to verify both Dockerfile and Dockerfile-full
- update the `.github/workflows/test.yml` to use superlinter v4 (see what to change from https://github.com/OpenLiberty/guide-maven-intro/pull/144/files)
- replace `CONTRIBUTING.md` as same as https://raw.githubusercontent.com/OpenLiberty/guide-microprofile-graphql/version-update-mp5/CONTRIBUTING.md

2022-06-08 21:22 UTC, gkwan-ibm reviewed
@uhryniuk 
- the statement is too long, break it with comma or multiple statments
  > This is recommended for development but when deploying to production it’s recommended to use a parent image with the kernel-slim tag to provide a bare minimum server with the ability to add the features required by the application.
 - "...destination directory . " -> "destination directory."
 - suggest to change the command `docker exec -it system /opt/ol/wlp/bin/productInfo featureInfo` to `inventory` and the output

2022-06-09 19:28 UTC, gkwan-ibm requested changes
@uhryniuk 
- the '/config/' should be `/config/`
  >  "...copied to the '/config/` destination directory. " 
- "... `Podman` containers:..." - "... containers:..."
  - occur in several places 
- "... new `Podman` images..." -> " ...new container images..."
  - occur in several places

2022-06-10 13:03 UTC, gkwan-ibm approved these changes

2022-06-13 10:40 UTC, ramkumar-k-9286 commented on README.adoc
> +As previously mentioned, the parent image used in each `Dockerfile` contains the `full` tag which includes all of the Liberty features. This is recommended for development but when deploying to produ
```suggestion
As mentioned previously, the parent image that is used in each `Dockerfile` contains the `full` tag, which includes all of the Liberty features. This parent image with the `full` tag is recommended for development, but while deploying to production it is recommended to use a parent image with the `kernel-slim` tag. The `kernel-slim` tag provides a bare minimum server with the ability to add the features required by the application.
```

2022-06-13 11:00 UTC, ramkumar-k-9286 commented on README.adoc
> +Replace the parent image with [hotspot=kernel-slim file=0]`icr.io/appcafe/open-liberty:kernel-slim-java11-openj9-ubi` at the top of your Dockerfile. This image contains the `kernel-slim` tag that's r
```suggestion
Replace the parent image with [hotspot=kernel-slim file=0]`icr.io/appcafe/open-liberty:kernel-slim-java11-openj9-ubi` at the top of your `Dockerfile`. This image contains the `kernel-slim` tag that is recommended when deploying to production.
```

2022-06-13 11:03 UTC, ramkumar-k-9286 commented on README.adoc
> +Place [hotspot=features file=0]`RUN features.sh` command after the `COPY` command that the configuration file is copied to the `/config/` destination directory. The `features.sh` script adds the Libe
Please rephrase this sentence. it is confusing.
Place [hotspot=features file=0]`RUN features.sh` command after the `COPY` command that the configuration file is copied to the `/config/` destination directory.

2022-06-13 11:05 UTC, ramkumar-k-9286 commented on README.adoc
> +Verify that the images have built by executing the following command to list all the local `Docker` images:
```suggestion
Verify that the images have been built by executing the following command to list all the local `Docker` images:
```

2022-06-13 11:06 UTC, ramkumar-k-9286 commented on README.adoc
> +Once your `Docker` containers are running, run the following command to see the list of the required features installed by `features.sh`:
```suggestion
Once your `Docker` containers are running, run the following command to see the list of required features installed by `features.sh`:
```

2022-06-13 11:08 UTC, ramkumar-k-9286 commented on README.adoc
> +To ensure your containers are working properly, try accessing the `system` service to show the system properties of the running JVM.
```suggestion
To ensure that your containers are working properly, try accessing the `system` service to show the system properties of the running JVM.
```

2022-06-13 11:08 UTC, ramkumar-k-9286 commented on README.adoc
> +Next, replace `[system-ip-address]` with the IP address that you obtained earlier and add your localhost system properties to the `inventory` service by visting:
```suggestion
Next, replace `[system-ip-address]` with the IP address that you obtained earlier and add your localhost system properties to the `inventory` service by visiting:
```

2022-06-13 11:09 UTC, ramkumar-k-9286 commented on README.adoc
> +Then verify the addition of your localhost system properties to your `inventory` service.
```suggestion
Then, verify the addition of your localhost system properties to your `inventory` service. 
```

2022-06-13 11:10 UTC, ramkumar-k-9286 commented on README.adoc
> +The **system** service which shows the system properties of the running JVM, is now available to be accessed at **http://localhost:9080/system/properties**. Run the following curl command:
```suggestion
The **system** service which shows the system properties of the running JVM is now available to be accessed at **http://localhost:9080/system/properties**. Run the following curl command:
```

2022-06-13 11:11 UTC, ramkumar-k-9286 commented on README.adoc
> +Then, verify the addition of your localhost system properties to the **inventory** service at **http://localhost:9081/inventory/systems** . Run the following curl command:
```suggestion
Then, verify the addition of your localhost system properties to the **inventory** service at **http://localhost:9081/inventory/systems**. Run the following curl command:
```

2022-06-14 06:38 UTC, ramkumar-k-9286 commented on README.adoc
> +Ensure that you repeat these instructions again for the `system` service.
```suggestion
Ensure that you repeat these instructions for the `system` service.
```

2022-06-14 06:41 UTC, ramkumar-k-9286 commented on README.adoc
> +Verify that the images have been built by executing the following command to list all the local `Docker` images:
```suggestion
Verify that the images have been built by executing the following command to list all the local `Docker` images:
```

2022-06-14 17:01 UTC, ramkumar-k-9286 approved these changes

2022-06-14 17:02 UTC, gkwan-ibm approved these changes

2022-06-14 17:03 UTC, merged